const bcrypt = require('bcryptjs');
const config = require("../config/config");
const home = require("./homeRoute");
const loginForm = require("./login");
const addTwitsPost = require("./addTwits");
const addTwitForm = require("./addTwitForm");
const loginUser = require("./userLogin");
const getTwitDetails = require("./getTwitDetails");
const userRegistration = require("./userRegistration");
const getTwits = require("./getTwits");
const getUserRegForm = require("./getUserRegForm");
const viewUsers = require("./viewUsers");
const userLogout = require("./userLogout");
const viewUser = require("./viewUserDetail");
const invalidGet = require("./invalidGet");
const invalidPost = require("./invalidPost");
const tokenHandler = require("./tokenHandler");
const getEditTwit = require("./getEditTwitF");
const updateTwit = require("./updateTwit");
const deleteConfirm = require("./deleteConfirmation");
const deleteTwit = require("./deleteTwit");
const snickUserDetail = require("./snickUserDetail");
const uploadAvata = require("./uploadAvata")
const updateAvata = require("./updateAvata")
exports.homeRoute = home.homeRoute;
exports.login = loginForm.login;
exports.addTwits = addTwitsPost.addTwits;
exports.getAddTwit = addTwitForm.getAddTwit;
exports.userLogin = loginUser.userLogin;
exports.twitDetails = getTwitDetails.twitDetails;
exports.registerUser = userRegistration.registerUser;
exports.viewTwits = getTwits.viewTwits;
exports.createUser = getUserRegForm.createUser;
exports.viewUser = viewUsers.viewUser;
exports.logout = userLogout.logout;
exports.userDetails = viewUser.userDetails;
exports.invalidGetRequest = invalidGet.invalidGetRequest;
exports.invalidPostRequest = invalidPost.invalidPostRequest;
exports.authenticateToken = tokenHandler.authenticateToken;
exports.editTwit = getEditTwit.getEditTwitForm;
exports.UpdateTwit = updateTwit.UpdateTwit;
exports.deleteConfirmation = deleteConfirm.deleteConfirmation;
exports.deleteTwit = deleteTwit.deleteNow
exports.userDetailsSnickPic = snickUserDetail.userDetailsSnickPic;
exports.uploadAvata = uploadAvata.uploadAvata
exports.updateAvata = updateAvata.updateAvata;
